name: CI
on:
  - push
  - pull_request

jobs:

  test:
    name: Test
    # Has Node.js 18 pre-installed
    # https://github.com/actions/runner-images/blob/ubuntu22/20231030.2/images/linux/Ubuntu2204-Readme.md
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test
